<a href="https://colab.research.google.com/github/hyrinn/Deep_Learning/blob/main/%EC%99%80%EC%9D%B8_%ED%92%88%EC%A7%88_%EC%98%88%EC%B8%A1_%EB%AA%A8%EB%8D%B8_%EC%84%B1%EB%8A%A5_%EA%B0%9C%EC%84%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**[5주차]과제**
- 아래의 과제1)의 코드를 완성하시오.
- 모든 코드의 결과를 출력하여, .ipynb의 링크를 **[5주차]/[5주차]과제**에 제출하시오.\
(실습 제출 예시: 5주차_2020XXXX_이름.ipynb 코드 링크)

In [1]:
print("조효린", "2243186")

조효린 2243186

In [2]:
from google.colab import auth

auth.authenticate_user()
!gcloud config get-value account

2243186@donga.ac.kr

In [3]:
from google.colab import drive
drive.mount('/content/Drive/')

Mounted at /content/Drive/

In [4]:
#작업폴더 경로 참고 : data파일이 있는 폴더의 경로를 작성
workspace_path = '/content/Drive/MyDrive/딥러닝'

# [과제 1] activation func, hyper-parameter, optimizer등을 변경하여 와인 품질(quality)를 예측하는 모델의 accuracy(정확도)를 0.5 이상의 성능을 달성하여라.

## 조건 :
1. epoch 수는 최대 20으로 제한
2. 모델의 레이어는 2개(입력층, 출력층)로 제한
3. 입력층의 노드수는 256개로 하고 input_shape은 xTrain.shape[1]과 동일한 값으로 설정할 것

    예시) layer추가
```python
# 입력층 예시
netwrok.add(tf.keras.layers.Dense(노드 수, activation_func='activation_func', input_shape=xTrain.shape[1], kernel_initializer=initializer))
# 출력층 예시
network.add(tf.keras.layers.Dense(노드 수, activation='activation_func', kernel_initializer=initializer))

##- 개선사항을 작성해 주세요 :

activation_func 는 relu, softmax
batch_size = 30 , epochs = 20
optimizer = adam
hyper-parameter = 256, 7

출력층 activation_func에서 softmax , sigmoid는 큰 차이 없음
batch_size 가 커지니까 정확도가 조금 높아짐

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [7]:
red_df = pd.read_csv(os.path.join(workspace_path,'winequality-red.csv'), sep=';', header=0, engine='python')
red_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [8]:
white_df = pd.read_csv(os.path.join(workspace_path,'winequality-white.csv'), sep=';', header=0, engine='python')
white_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [9]:
wine =  pd.concat([red_df, white_df])

In [10]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6497 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 659.9 KB

In [11]:
sorted(wine.quality.unique())

[np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [12]:
wine.quality.value_counts()

quality
6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: count, dtype: int64

In [13]:
# 코드를 작성해 주세요
# 레이블링 인코딩 필요
# 힌트 : ?? = ??.apply(lambda x: x-3)

white_df['quality'] = white_df['quality'].apply(lambda x: x - 3)

In [14]:
sorted(wine.quality.unique())

[np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [15]:
# 코드를 작성해 주세요
# 힌트 : 와인의 품질을 예측하는 모델이므로 훈련 데이터셋도 품질에 훈련셋으로 준비되어야 함
# xTrain = ??.drop(???, axis=1)
# yTrain = ??

xTrain = white_df.drop('quality', axis=1)
yTrain = white_df['quality']

In [16]:
xTrain, xTest, yTrain, yTest = train_test_split(xTrain, yTrain, test_size=0.2)

In [17]:
# 실험 결과 재현을 위한 seed 고정
SEED = 4
os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['TF_DETERMINISTIC_OPS'] = '1'
tf.random.set_seed(SEED)
initializer = tf.keras.initializers.GlorotUniform(seed=SEED)

In [18]:
def build_model():
  network = tf.keras.models.Sequential()
  network.add(tf.keras.layers.Dense(256, activation='relu', input_shape=(xTrain.shape[1],)))
  network.add(tf.keras.layers.Dense(7, activation='softmax', kernel_initializer=initializer))


  network.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

  return network

In [25]:
model = build_model()

history = model.fit(xTrain, yTrain, epochs=20, batch_size=30, validation_split=0.25)

Epoch 1/20

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

98/98 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.4098 - loss: 2.1785 - val_accuracy: 0.4490 - val_loss: 1.3709
Epoch 2/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4156 - loss: 1.3872 - val_accuracy: 0.4571 - val_loss: 1.2937
Epoch 3/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4258 - loss: 1.3512 - val_accuracy: 0.4612 - val_loss: 1.2577
Epoch 4/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4295 - loss: 1.3302 - val_accuracy: 0.4653 - val_loss: 1.2427
Epoch 5/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4319 - loss: 1.3193 - val_accuracy: 0.4653 - val_loss: 1.2401
Epoch 6/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4333 - loss: 1.3095 - val_accuracy: 0.4694 - val_loss: 1.2229
Epoch 7/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4346 - loss: 1.3035 - val_accuracy: 0.4663 - val_loss: 1.2127
Epoch 8/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4404 - loss: 1.2922 - val_accuracy: 0.4796 - val_loss: 1.2069
Epoch 9/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4381 - loss: 1.2825 - val_accuracy: 0.4816 - val_loss: 1.2039
Epoch 10/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4418 - loss: 1.2798 - val_accuracy: 0.4806 - val_loss: 1.1983
Epoch 11/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4479 - loss: 1.2670 - val_accuracy: 0.4765 - val_loss: 1.1922
Epoch 12/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4486 - loss: 1.2616 - val_accuracy: 0.4816 - val_loss: 1.1858
Epoch 13/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4506 - loss: 1.2556 - val_accuracy: 0.4816 - val_loss: 1.1816
Epoch 14/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.4496 - loss: 1.2534 - val_accuracy: 0.4929 - val_loss: 1.1763
Epoch 15/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.4479 - loss: 1.2472 - val_accuracy: 0.4867 - val_loss: 1.1745
Epoch 16/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4500 - loss: 1.2438 - val_accuracy: 0.4969 - val_loss: 1.1678
Epoch 17/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4537 - loss: 1.2436 - val_accuracy: 0.4878 - val_loss: 1.1658
Epoch 18/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4554 - loss: 1.2383 - val_accuracy: 0.4918 - val_loss: 1.1617
Epoch 19/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.4564 - loss: 1.2359 - val_accuracy: 0.4929 - val_loss: 1.1588
Epoch 20/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4558 - loss: 1.2314 - val_accuracy: 0.4990 - val_loss: 1.1549

In [26]:
test_loss, test_acc = model.evaluate(xTest, yTest)

31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5143 - loss: 1.1222

In [27]:
print('테스트 정확도 : ', round(test_acc,3))

테스트 정확도 :  0.514